version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
  app:
    build: .
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      WB_API_URL: ${WB_API_URL}
      WB_BEARER_TOKEN: ${WB_BEARER_TOKEN}
      GOOGLE_SHEET_API_KEY: ${GOOGLE_SHEET_API_KEY}
      GOOGLE_SHEET_CREDENTIALS_PATH: ${GOOGLE_SHEET_CREDENTIALS_PATH}
    depends_on:
      - db
    ports:
      - "3000:3000"
